alias tail="tail -40"
alias du="du -h"
alias df="df -h"
alias screen="TERM=screen screen"
alias screen="screen -DDR"
alias ls="ls -GF --color=auto"
alias la="ls -a"
alias ll="ls -lh"
alias lla="ll -a"
alias gitka="gitk --all &"
alias greps="grep -EHIirn"
alias home="cd ~"
alias ngmms="cd ~/git_NGMMS"
alias vi="nvim"
alias vim="nvim"
