alias ls="ls -GF"
alias la="ls -a"
alias ll="ls -lhGF"
alias lla="ls -la"
alias tail="tail -40"
alias du="du -h"
alias df="df -h"
alias screen="TERM=screen screen"
alias screen="screen -DDR"
alias qmake="qmake -spec macx-g++"
